### PR TITLE
Added filtering by date to buildQuery

### PR DESCRIPTION
**Pull request by enymawse**
Love the project and would like to contribute. I think this simple functionality would be a great addition to the API.

This PR implements date filtering using the following comparison methods: EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, IS_NULL, and NOT_NULL.

Open to feedback.

### CODE REVIEW

**Comment by enymawse** [comment]
Looks like the functionality of [actions/upload-artifact:v2](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/) was finally switched off.

**Comment by InfiniteStash** [comment]
> Looks like the functionality of [actions/upload-artifact:v2](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/) was finally switched off.

Yep! A fix was merged in yesterday so if you rebase it should build correctly.

**Comment by enymawse** [comment]
@InfiniteStash Sort of new to this but do I need to squash the commits before the workflows will run again? It seems like they are just awaiting approval.

**Comment by enymawse** [comment]
@InfiniteStash any word on a merge?

**Pull request merged**
