### PR TITLE
Scene edit

### PR DESCRIPTION
**Pull request by WithoutPants**
Adds support for creating, modifying and deleting scenes via the Edit system. Backend support for merging is also present but has not been well exercised, and I have not yet added UI support for it.

### CODE REVIEW

**Comment by peolic** [comment]
Looks like an empty modify edit can be submitted with just an edit note and no changes.

**Comment by ghost** [comment]
> Looks like an empty modify edit can be submitted with just an edit note and no changes.

You can submit an empty edit, but the server should throw an error if there's no changes. Are you not getting an error?

**Comment by peolic** [comment]
Ah, digging into the raw data, I found this in the edit row.
(the scene description is `NULL` inside the database)

<details>
<summary><code>old_data</code></summary>

```json
{
    "added_fingerprints": null,
    "added_images": null,
    "added_performers": null,
    "added_tags": null,
    "added_urls": null,
    "date": null,
    "details": null,
    "director": null,
    "duration": null,
    "removed_fingerprints": null,
    "removed_images": null,
    "removed_performers": null,
    "removed_tags": null,
    "removed_urls": null,
    "studio_id": null,
    "title": null
}
```
</details>

<details>
<summary><code>new_data</code></summary>

```json
{
    "added_fingerprints": null,
    "added_images": null,
    "added_performers": null,
    "added_tags": null,
    "added_urls": null,
    "date": null,
    "details": "",
    "director": null,
    "duration": null,
    "removed_fingerprints": null,
    "removed_images": null,
    "removed_performers": null,
    "removed_tags": null,
    "removed_urls": null,
    "studio_id": null,
    "title": null
}
```
</details>

**Comment by ghost** [comment]
> Ah, digging into the raw data, I found this in the edit row.
> (the scene description is `NULL` inside the database)

That makes sense, thanks. I've updated the edit logic to set empty strings to null so we avoid the issue.

**Pull request merged**
