### PR TITLE
Favorite studios and performers

### PR DESCRIPTION
**Pull request by ghost**
Studios and performers can be favorited by clicking the star on the entity page. Didn't have time to implement it, but the idea is that you can filter entity lists and edits, by fav status.

TODO:
- [x] Filter performer list by fav status
- [x] Filter studio list by fav status
- [x] Filter edits by performer favoriting
- [x] Filter edits by studio favoriting

### CODE REVIEW

**Comment by ghost** [comment]
Indexes on edit fav search will probably have to be revisited once there's test data. Performance is great currently, but I'm not entirely sure it scales.

**Comment by peolic** [comment]
Visually I have one note, probably out of scope for this PR:
The Performer Info (Header) is really packed, and with the buttons on the right, sometimes even the name does not fit in a single row. Maybe just the buttons should be elsewhere...

**Comment by ghost** [comment]
> Visually I have one note, probably out of scope for this PR: The Performer Info (Header) is really packed, and with the buttons on the right, sometimes even the name does not fit in a single row. Maybe just the buttons should be elsewhere...

I've shoved the buttons above the info card so the name gets the full width. It doesn't look great, but neither do the alternatives. The entire view needs to be redesigned but that's beyond the scope of this PR.

**Comment by peolic** [comment]
> It doesn't look great, but neither do the alternatives. The entire view needs to be redesigned but that's beyond the scope of this PR.

:+1:

I have a suggestion and a request based on the latest commit:
The info card and the photo can be made to line up at the top, and quite easily as it turns out.

firefox_m41bKNotpY

And the request, add a class to `PerformerInfo`.
Thanks!

---

```diff
diff --git a/frontend/src/pages/performers/performerInfo/PerformerInfo.tsx b/frontend/src/pages/performers/performerInfo/PerformerInfo.tsx
index e080f19..8de9adf 100644
--- a/frontend/src/pages/performers/performerInfo/PerformerInfo.tsx
+++ b/frontend/src/pages/performers/performerInfo/PerformerInfo.tsx
@@ -31,11 +31,13 @@ import {
 import { GenderIcon, PerformerName, Tooltip } from "src/components/fragments";
 import ImageCarousel from "src/components/imageCarousel";

+const CLASSNAME = "PerformerInfo";
+
 const PerformerInfo: FC<{ performer: Performer }> = ({ performer }) => {
   const auth = useContext(AuthContext);

   return (
-    <Row>
+    <Row className={CLASSNAME}>
       <Col xs={6}>
         {canEdit(auth?.user) && !performer.deleted && (
           <div className="text-end">
diff --git a/frontend/src/pages/performers/styles.scss b/frontend/src/pages/performers/styles.scss
index 0464a50..0da9d67 100644
--- a/frontend/src/pages/performers/styles.scss
+++ b/frontend/src/pages/performers/styles.scss
@@ -18,7 +18,7 @@

 .performer-photo {
   height: 470px;
-  margin-top: 5px;
+  margin-top: auto;
 }

 .performer-filter {

```

**Pull request merged**
